# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "capistrano-templates"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Huiming Teo"]
  s.date = "2012-06-11"
  s.description = "A collection of commonly used Capistrano templates."
  s.email = "teohuiming@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "capistrano-templates.gemspec",
    "lib/captify_template.rb",
    "templates/rails-basic/config/deploy.rb",
    "templates/rails-basic/config/deploy/production.rb",
    "templates/rails-basic/config/deploy/staging.rb"
  ]
  s.homepage = "http://github.com/teohm/capistrano-templates"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "A collection of commonly used Capistrano templates."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<capistrano>, [">= 0"])
      s.add_runtime_dependency(%q<captify>, [">= 0"])
      s.add_runtime_dependency(%q<rvm-capistrano>, [">= 0"])
      s.add_runtime_dependency(%q<capistrano-helpers>, [">= 0"])
      s.add_runtime_dependency(%q<capistrano_colors>, [">= 0"])
      s.add_runtime_dependency(%q<capistrano-ssh-helpers>, [">= 0"])
      s.add_runtime_dependency(%q<capistrano-shared-helpers>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
    else
      s.add_dependency(%q<capistrano>, [">= 0"])
      s.add_dependency(%q<captify>, [">= 0"])
      s.add_dependency(%q<rvm-capistrano>, [">= 0"])
      s.add_dependency(%q<capistrano-helpers>, [">= 0"])
      s.add_dependency(%q<capistrano_colors>, [">= 0"])
      s.add_dependency(%q<capistrano-ssh-helpers>, [">= 0"])
      s.add_dependency(%q<capistrano-shared-helpers>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    end
  else
    s.add_dependency(%q<capistrano>, [">= 0"])
    s.add_dependency(%q<captify>, [">= 0"])
    s.add_dependency(%q<rvm-capistrano>, [">= 0"])
    s.add_dependency(%q<capistrano-helpers>, [">= 0"])
    s.add_dependency(%q<capistrano_colors>, [">= 0"])
    s.add_dependency(%q<capistrano-ssh-helpers>, [">= 0"])
    s.add_dependency(%q<capistrano-shared-helpers>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
  end
end

